### ISSUE TITLE
Undefined callback error

### ISSUE THREAD

**Issue by sarus** [polarityio/cyber-risk-analytics#1]
```
  "stack": [
    "ReferenceError: callback is not defined",
    "    at getAuthToken (/app/polarity-server/integrations/cyber-risk-analytics/integration.js:131:13)",
    "    at Request.request [as _callback] (/app/polarity-server/integrations/cyber-risk-analytics/integration.js:107:13)",
    "    at Request.self.callback (/app/polarity-server/integrations/cyber-risk-analytics/node_modules/request/request.js:185:22)",
    "    at Request.emit (events.js:189:13)",
    "    at Request.<anonymous> (/app/polarity-server/integrations/cyber-risk-analytics/node_modules/request/request.js:1161:10)",
    "    at Request.emit (events.js:189:13)",
    "    at IncomingMessage.<anonymous> (/app/polarity-server/integrations/cyber-risk-analytics/node_modules/request/request.js:1083:12)",
    "    at Object.onceWrapper (events.js:277:13)",
    "    at IncomingMessage.emit (events.js:194:15)",
    "    at endReadableNT (_stream_readable.js:1125:12)"

```

**Comment by penwoodjon** [comment]
A fix to this has been pushed and is currently in master
